// dsh-better-git-worktree — versioned Host entry (development reload lever).
// Generated by scripts/dev-reload-host.mjs - see the plugin README.
export { default, inject, name } from './host-main.mjs';
